server:
  port: 3099

spring:
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

tebi:
  access_key: {YOUR_ACCESS_KEY}
  secret_key: {YOUR_SECRET_KEY}
  bucket: {YOUR_BUCKET_NAME}
  endpoint_url: https://s3.tebi.io
  region: {YOUR_REGION}

r2:
  access_key: {YOUR_ACCESS_KEY}
  secret_key: {YOUR_SECRET_KEY}
  bucket: {YOUR_BUCKET_NAME}
  endpoint_url: https://{YOUR_ACCOUNT_ID}.r2.cloudflarestorage.com
